// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sectxt_parse
SEXP sectxt_parse(std::string content);
RcppExport SEXP _securitytxt_sectxt_parse(SEXP contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type content(contentSEXP);
    rcpp_result_gen = Rcpp::wrap(sectxt_parse(content));
    return rcpp_result_gen;
END_RCPP
}
// sectxt_raw
std::string sectxt_raw(SEXP x);
RcppExport SEXP _securitytxt_sectxt_raw(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sectxt_raw(x));
    return rcpp_result_gen;
END_RCPP
}
// sectxt_keys
std::vector< std::string > sectxt_keys(SEXP x);
RcppExport SEXP _securitytxt_sectxt_keys(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sectxt_keys(x));
    return rcpp_result_gen;
END_RCPP
}
// sectxt_info
DataFrame sectxt_info(SEXP x);
RcppExport SEXP _securitytxt_sectxt_info(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sectxt_info(x));
    return rcpp_result_gen;
END_RCPP
}
// sectxt_url
std::string sectxt_url(std::string url);
RcppExport SEXP _securitytxt_sectxt_url(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(sectxt_url(url));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_securitytxt_sectxt_parse", (DL_FUNC) &_securitytxt_sectxt_parse, 1},
    {"_securitytxt_sectxt_raw", (DL_FUNC) &_securitytxt_sectxt_raw, 1},
    {"_securitytxt_sectxt_keys", (DL_FUNC) &_securitytxt_sectxt_keys, 1},
    {"_securitytxt_sectxt_info", (DL_FUNC) &_securitytxt_sectxt_info, 1},
    {"_securitytxt_sectxt_url", (DL_FUNC) &_securitytxt_sectxt_url, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_securitytxt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
