# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse security.txt
#'
#' @noRd
#'
sectxt_parse <- function(content) {
    .Call('_securitytxt_sectxt_parse', PACKAGE = 'securitytxt', content)
}

sectxt_raw <- function(x) {
    .Call('_securitytxt_sectxt_raw', PACKAGE = 'securitytxt', x)
}

sectxt_keys <- function(x) {
    .Call('_securitytxt_sectxt_keys', PACKAGE = 'securitytxt', x)
}

#' Retrieve a data frame of security.txt keys/values
#'
#' @md
#' @param x a parsed `security.txt` created with [sec_parse()]
#' @return data frame
#' @export
sectxt_info <- function(x) {
    .Call('_securitytxt_sectxt_info', PACKAGE = 'securitytxt', x)
}

#' Determine security.txt URL for a given site/URL
#'
#' Provide any URL for a resource and retrieve the URL for
#' the `security.txt` file. Strips off extraneous URL
#' components and appends `.well-known/security.txt`.
#'
#' @md
#' @param url URL
#' @return character vector
#' @export
#' @examples
#' sectxt_url("https://securitytxt.org/this/that/the/other.html")
sectxt_url <- function(url) {
    .Call('_securitytxt_sectxt_url', PACKAGE = 'securitytxt', url)
}

